# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\display_photo_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Display_Images(object):
    def setupUi(self, Display_Images):
        Display_Images.setObjectName("Display_Images")
        Display_Images.resize(1024, 600)
        self.label_image_1 = QtWidgets.QLabel(Display_Images)
        self.label_image_1.setGeometry(QtCore.QRect(25, 146, 308, 308))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(30)
        self.label_image_1.setFont(font)
        self.label_image_1.setText("")
        self.label_image_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_1.setObjectName("label_image_1")
        self.label_image_2 = QtWidgets.QLabel(Display_Images)
        self.label_image_2.setGeometry(QtCore.QRect(358, 146, 308, 308))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(30)
        self.label_image_2.setFont(font)
        self.label_image_2.setText("")
        self.label_image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_2.setObjectName("label_image_2")
        self.label_image_3 = QtWidgets.QLabel(Display_Images)
        self.label_image_3.setGeometry(QtCore.QRect(691, 146, 308, 308))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(30)
        self.label_image_3.setFont(font)
        self.label_image_3.setText("")
        self.label_image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_3.setObjectName("label_image_3")
        self.pushButton_to_home = QtWidgets.QPushButton(Display_Images)
        self.pushButton_to_home.setGeometry(QtCore.QRect(387, 500, 250, 65))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(22)
        self.pushButton_to_home.setFont(font)
        self.pushButton_to_home.setObjectName("pushButton_to_home")
        self.label_main_text = QtWidgets.QLabel(Display_Images)
        self.label_main_text.setGeometry(QtCore.QRect(0, 30, 1024, 71))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(30)
        self.label_main_text.setFont(font)
        self.label_main_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_text.setObjectName("label_main_text")
        self.background = QtWidgets.QLabel(Display_Images)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        self.background.setFont(font)
        self.background.setText("")
        self.background.setObjectName("background")
        self.background.raise_()
        self.label_image_1.raise_()
        self.label_image_2.raise_()
        self.label_image_3.raise_()
        self.pushButton_to_home.raise_()
        self.label_main_text.raise_()

        self.retranslateUi(Display_Images)
        QtCore.QMetaObject.connectSlotsByName(Display_Images)

    def retranslateUi(self, Display_Images):
        _translate = QtCore.QCoreApplication.translate
        Display_Images.setWindowTitle(_translate("Display_Images", "Form"))
        self.pushButton_to_home.setText(_translate("Display_Images", "Back to Home "))
        self.label_main_text.setText(_translate("Display_Images", "Your Pictures!"))
