# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\home_screen_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1024, 600)
        self.background = QtWidgets.QLabel(Home)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_header = QtWidgets.QLabel(Home)
        self.label_header.setGeometry(QtCore.QRect(220, 50, 551, 81))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.pushButton_take_photo = QtWidgets.QPushButton(Home)
        self.pushButton_take_photo.setGeometry(QtCore.QRect(350, 290, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        self.pushButton_take_photo.setFont(font)
        self.pushButton_take_photo.setObjectName("pushButton_take_photo")
        self.pushButton_to_launch = QtWidgets.QPushButton(Home)
        self.pushButton_to_launch.setGeometry(QtCore.QRect(30, 480, 271, 91))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_to_launch.setFont(font)
        self.pushButton_to_launch.setObjectName("pushButton_to_launch")

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.label_header.setText(_translate("Home", "Welcome to the Home Screen "))
        self.pushButton_take_photo.setText(_translate("Home", "Take Photo"))
        self.pushButton_to_launch.setText(_translate("Home", "Go Back to Launch Screen "))
