# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\home_screen_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1024, 600)
        self.background = QtWidgets.QLabel(Home)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_header = QtWidgets.QLabel(Home)
        self.label_header.setGeometry(QtCore.QRect(0, 35, 1021, 111))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(31)
        font.setBold(False)
        font.setWeight(50)
        self.label_header.setFont(font)
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.pushButton_take_photo = QtWidgets.QPushButton(Home)
        self.pushButton_take_photo.setGeometry(QtCore.QRect(310, 304, 400, 111))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(35)
        self.pushButton_take_photo.setFont(font)
        self.pushButton_take_photo.setObjectName("pushButton_take_photo")
        self.label_header_2 = QtWidgets.QLabel(Home)
        self.label_header_2.setGeometry(QtCore.QRect(0, 464, 1021, 111))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_header_2.setFont(font)
        self.label_header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header_2.setObjectName("label_header_2")
        self.label_header_3 = QtWidgets.QLabel(Home)
        self.label_header_3.setGeometry(QtCore.QRect(0, 154, 1021, 101))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_header_3.setFont(font)
        self.label_header_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header_3.setObjectName("label_header_3")

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.label_header.setText(_translate("Home", "Get Ready to Strike a Pose! "))
        self.pushButton_take_photo.setText(_translate("Home", "Start"))
        self.label_header_2.setText(_translate("Home", "NOTICE:By pressing Start, you consent to being photographed.\n"
"Digital copies of all photos are saved and provided to the event host"))
        self.label_header_3.setText(_translate("Home", "We\'ll take 3 photos in a row, so keep those smiles coming!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QWidget()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
