# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\launch_screen_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Launch(object):
    def setupUi(self, Launch):
        Launch.setObjectName("Launch")
        Launch.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(Launch)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_test.setGeometry(QtCore.QRect(280, 280, 441, 151))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(16)
        self.pushButton_test.setFont(font)
        self.pushButton_test.setObjectName("pushButton_test")
        self.label_test = QtWidgets.QLabel(self.centralwidget)
        self.label_test.setGeometry(QtCore.QRect(390, 110, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_test.setFont(font)
        self.label_test.setObjectName("label_test")
        Launch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Launch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        Launch.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Launch)
        self.statusbar.setObjectName("statusbar")
        Launch.setStatusBar(self.statusbar)

        self.retranslateUi(Launch)
        QtCore.QMetaObject.connectSlotsByName(Launch)

    def retranslateUi(self, Launch):
        _translate = QtCore.QCoreApplication.translate
        Launch.setWindowTitle(_translate("Launch", "MainWindow"))
        self.pushButton_test.setText(_translate("Launch", "Push this for a secret"))
        self.label_test.setText(_translate("Launch", "THIS IS A SECRET "))
