# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\launch_screen_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Launch(object):
    def setupUi(self, Launch):
        Launch.setObjectName("Launch")
        Launch.resize(1024, 600)
        self.background = QtWidgets.QLabel(Launch)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_test = QtWidgets.QLabel(Launch)
        self.label_test.setGeometry(QtCore.QRect(0, 30, 1021, 211))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(29)
        font.setBold(False)
        font.setWeight(50)
        self.label_test.setFont(font)
        self.label_test.setAlignment(QtCore.Qt.AlignCenter)
        self.label_test.setObjectName("label_test")
        self.pushButton_to_home = QtWidgets.QPushButton(Launch)
        self.pushButton_to_home.setGeometry(QtCore.QRect(564, 429, 400, 101))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_to_home.setFont(font)
        self.pushButton_to_home.setObjectName("pushButton_to_home")
        self.pushButton_change_background = QtWidgets.QPushButton(Launch)
        self.pushButton_change_background.setGeometry(QtCore.QRect(60, 429, 400, 101))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_change_background.setFont(font)
        self.pushButton_change_background.setObjectName("pushButton_change_background")
        self.lineEdit_party = QtWidgets.QLineEdit(Launch)
        self.lineEdit_party.setGeometry(QtCore.QRect(150, 270, 700, 100))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(25)
        self.lineEdit_party.setFont(font)
        self.lineEdit_party.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_party.setObjectName("lineEdit_party")

        self.retranslateUi(Launch)
        QtCore.QMetaObject.connectSlotsByName(Launch)

    def retranslateUi(self, Launch):
        _translate = QtCore.QCoreApplication.translate
        Launch.setWindowTitle(_translate("Launch", "Form"))
        self.label_test.setText(_translate("Launch", "Please enter the party name and\n"
"select color before starting session. "))
        self.pushButton_to_home.setText(_translate("Launch", "Go To Home Screen "))
        self.pushButton_change_background.setText(_translate("Launch", "Change Color "))
        self.lineEdit_party.setText(_translate("Launch", "Party Name"))
