# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\launch_screen_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Launch(object):
    def setupUi(self, Launch):
        Launch.setObjectName("Launch")
        Launch.resize(1024, 600)
        self.pushButton_test = QtWidgets.QPushButton(Launch)
        self.pushButton_test.setGeometry(QtCore.QRect(260, 210, 441, 151))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_test.setFont(font)
        self.pushButton_test.setObjectName("pushButton_test")
        self.background = QtWidgets.QLabel(Launch)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_test = QtWidgets.QLabel(Launch)
        self.label_test.setGeometry(QtCore.QRect(270, 110, 441, 101))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_test.setFont(font)
        self.label_test.setAlignment(QtCore.Qt.AlignCenter)
        self.label_test.setObjectName("label_test")
        self.pushButton_to_home = QtWidgets.QPushButton(Launch)
        self.pushButton_to_home.setGeometry(QtCore.QRect(710, 460, 271, 91))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_to_home.setFont(font)
        self.pushButton_to_home.setObjectName("pushButton_to_home")
        self.pushButton_change_background = QtWidgets.QPushButton(Launch)
        self.pushButton_change_background.setGeometry(QtCore.QRect(70, 470, 271, 91))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_change_background.setFont(font)
        self.pushButton_change_background.setObjectName("pushButton_change_background")
        self.background.raise_()
        self.label_test.raise_()
        self.pushButton_test.raise_()
        self.pushButton_to_home.raise_()
        self.pushButton_change_background.raise_()

        self.retranslateUi(Launch)
        QtCore.QMetaObject.connectSlotsByName(Launch)

    def retranslateUi(self, Launch):
        _translate = QtCore.QCoreApplication.translate
        Launch.setWindowTitle(_translate("Launch", "Form"))
        self.pushButton_test.setText(_translate("Launch", "Push this for a secret"))
        self.label_test.setText(_translate("Launch", "This is a secret"))
        self.pushButton_to_home.setText(_translate("Launch", "Go To Home Screen "))
        self.pushButton_change_background.setText(_translate("Launch", "Change Background "))
