# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\send_email.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Send_Email(object):
    def setupUi(self, Send_Email):
        Send_Email.setObjectName("Send_Email")
        Send_Email.resize(1024, 600)
        self.background = QtWidgets.QLabel(Send_Email)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_main = QtWidgets.QLabel(Send_Email)
        self.label_main.setGeometry(QtCore.QRect(0, 60, 1024, 141))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(34)
        font.setBold(False)
        font.setWeight(50)
        self.label_main.setFont(font)
        self.label_main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main.setObjectName("label_main")
        self.pushButton_send = QtWidgets.QPushButton(Send_Email)
        self.pushButton_send.setGeometry(QtCore.QRect(574, 400, 350, 150))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setObjectName("pushButton_send")
        self.lineEdit_email = QtWidgets.QLineEdit(Send_Email)
        self.lineEdit_email.setGeometry(QtCore.QRect(100, 230, 824, 100))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(22)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton_skip = QtWidgets.QPushButton(Send_Email)
        self.pushButton_skip.setGeometry(QtCore.QRect(100, 400, 350, 150))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_skip.setFont(font)
        self.pushButton_skip.setObjectName("pushButton_skip")

        self.retranslateUi(Send_Email)
        QtCore.QMetaObject.connectSlotsByName(Send_Email)

    def retranslateUi(self, Send_Email):
        _translate = QtCore.QCoreApplication.translate
        Send_Email.setWindowTitle(_translate("Send_Email", "Form"))
        self.label_main.setText(_translate("Send_Email", "Enter Your Email"))
        self.pushButton_send.setText(_translate("Send_Email", "Send It!"))
        self.lineEdit_email.setText(_translate("Send_Email", "your.email@example.com"))
        self.pushButton_skip.setText(_translate("Send_Email", "Nevermind,\n"
"changed my mind."))
