# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\take_photo_screen_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TakePhoto(object):
    def setupUi(self, TakePhoto):
        TakePhoto.setObjectName("TakePhoto")
        TakePhoto.resize(1024, 600)
        self.background = QtWidgets.QLabel(TakePhoto)
        self.background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        self.background.setFont(font)
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_camera = QtWidgets.QLabel(TakePhoto)
        self.label_camera.setGeometry(QtCore.QRect(242, 30, 540, 540))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(40)
        self.label_camera.setFont(font)
        self.label_camera.setText("")
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera.setObjectName("label_camera")
        self.label_countdown = QtWidgets.QLabel(TakePhoto)
        self.label_countdown.setGeometry(QtCore.QRect(62, 220, 160, 160))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(75)
        self.label_countdown.setFont(font)
        self.label_countdown.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_countdown.setObjectName("label_countdown")
        self.label_countdown_2 = QtWidgets.QLabel(TakePhoto)
        self.label_countdown_2.setGeometry(QtCore.QRect(802, 220, 160, 160))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(75)
        self.label_countdown_2.setFont(font)
        self.label_countdown_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_countdown_2.setObjectName("label_countdown_2")

        self.retranslateUi(TakePhoto)
        QtCore.QMetaObject.connectSlotsByName(TakePhoto)

    def retranslateUi(self, TakePhoto):
        _translate = QtCore.QCoreApplication.translate
        TakePhoto.setWindowTitle(_translate("TakePhoto", "Form"))
        self.label_countdown.setText(_translate("TakePhoto", "0"))
        self.label_countdown_2.setText(_translate("TakePhoto", "0"))
