# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer_files\take_photo_screen_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TakePhoto(object):
    def setupUi(self, TakePhoto):
        TakePhoto.setObjectName("TakePhoto")
        TakePhoto.resize(1024, 600)
        self.background = QtWidgets.QLabel(TakePhoto)
        self.background.setGeometry(QtCore.QRect(-10, 10, 1024, 600))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        self.background.setFont(font)
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_main_text = QtWidgets.QLabel(TakePhoto)
        self.label_main_text.setGeometry(QtCore.QRect(50, 40, 431, 141))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(30)
        self.label_main_text.setFont(font)
        self.label_main_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_text.setObjectName("label_main_text")
        self.pushButton_to_home = QtWidgets.QPushButton(TakePhoto)
        self.pushButton_to_home.setGeometry(QtCore.QRect(80, 470, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(22)
        self.pushButton_to_home.setFont(font)
        self.pushButton_to_home.setObjectName("pushButton_to_home")
        self.label_counte = QtWidgets.QLabel(TakePhoto)
        self.label_counte.setGeometry(QtCore.QRect(570, 50, 350, 350))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(30)
        self.label_counte.setFont(font)
        self.label_counte.setAlignment(QtCore.Qt.AlignCenter)
        self.label_counte.setObjectName("label_counte")
        self.pushButton_take_pic = QtWidgets.QPushButton(TakePhoto)
        self.pushButton_take_pic.setGeometry(QtCore.QRect(630, 470, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(22)
        self.pushButton_take_pic.setFont(font)
        self.pushButton_take_pic.setObjectName("pushButton_take_pic")
        self.label_countdown = QtWidgets.QLabel(TakePhoto)
        self.label_countdown.setGeometry(QtCore.QRect(190, 210, 131, 111))
        font = QtGui.QFont()
        font.setFamily("Pacifico")
        font.setPointSize(30)
        self.label_countdown.setFont(font)
        self.label_countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_countdown.setObjectName("label_countdown")

        self.retranslateUi(TakePhoto)
        QtCore.QMetaObject.connectSlotsByName(TakePhoto)

    def retranslateUi(self, TakePhoto):
        _translate = QtCore.QCoreApplication.translate
        TakePhoto.setWindowTitle(_translate("TakePhoto", "Form"))
        self.label_main_text.setText(_translate("TakePhoto", "Taking a photo!!! "))
        self.pushButton_to_home.setText(_translate("TakePhoto", "Back to Home "))
        self.label_counte.setText(_translate("TakePhoto", "0"))
        self.pushButton_take_pic.setText(_translate("TakePhoto", "Take Photo"))
        self.label_countdown.setText(_translate("TakePhoto", "0"))
